	-- definiert Fehlertexte und Msg-Texte
	-- die Table ist ao aufgebaut 
	-- [nr] - die msg/error nummer
	--				nicht aufgelistet, da es "alles OK" anzeigt [0]
	-- = string
	--		der String besteht aus einem Schlüsselwort, getennt mit einem doppelpunkt ":" und dem Text
	--		Schlüsselworte
	--		ERROR: 	-> Ausgabe in minetest.log
	--		Info:		-> Ausgabe in minetest.log
	--		msg: 		-> Ausgabe erfolgt nur an den Spieler
rac.max_error = 100
rac.error_msg_text = {
		[1] = "ERROR: func: rac:msg_handling(err, name) - err ist keine Nummer",
		[2] = "ERROR: register_globalstep(function(dtime) - mehr als 2 Regionen!",
		[3] = "ERROR: func: rac:msg_handling(err, name) - die Nummer err ist größer als erlaubt!!!!",
		[4] = "ERROR: func: rac:create_data_string - no Player found for owner! ",
		[5] = "ERROR: func: rac:create_data_string - no region name submitted! ",
		[6] = "ERROR: func: rac:create_data_string - no claimable set! ",
		[7] = "ERROR: func: rac:create_data_string - no zone set! ", 
		[8] = "ERROR: func: rac:create_data_string - zone ist nichtt in der Liste! "..tostring(rac.allowed_zones),
		[9] = "ERROR: func: rac:create_data_string - no protected set! ",
		[10] = "ERROR: func: rac:create_data_string - no guests set! ",
		[11] = "ERROR: func: rac:create_data_string - no pvp set! ",
		[12] = "ERROR: func: rac:create_data_string - no mvp - Monsterdamage set! ",
		[13] = "ERROR: func: rac:create_data_string - effect ist nicht in der Liste! "..tostring(rac.allowed_effects),
		[14] = "ERROR: func: rac:create_data_string - no effect set! ",
		[15] = "ERROR: func: rac:set_region - übergebenes 'data' war weder table noch string!!!",
		[16] = "ERROR: func: rac:get_region_data_by_id - no region with this ID!",
		[17] = "ERROR: func: rac:get_owner_by_region_id - no owner in Region with this ID!",
		[18] = "ERROR: func: rac:region_set_attribute - No region with this ID! ",
		[19] = "ERROR: func: rac:region_set_attribute - The region_attribute did not fit!",
		[20] = "ERROR: func: rac:region_set_attribute - There is no Player with this name!",
		[21] = "ERROR: func: rac:region_set_attribute - Wrong effect! ",
		[22] = "ERROR: func: rac:region_set_attribute - You are not the owner of this region! ",
		[23] = "ERROR: func: rac:region_set_attribute - No Player with this name is in the guestlist! ",
		[24] = "ERROR: func: rac:region_set_attribute - no region with this ID!",
		[25] = "ERROR: func: rac:region_set_attribute - in update_regions_data! ", 
		[26] = "ERROR: func: rac:region_set_attribute - Dieser Gast ist schon auf der Gäste-Liste! ", 
		[27] = "ERROR: func: rac:region_set_attribute - The zone attribute did not fit!",
		[28] = "ERROR: func: rac:region_set_attribute - Claimable needs a boolean.",
		[29] = "ERROR: func: rac:region_set_attribute - The effect attribute did not fit!",
		[30] = "ERROR: func: rac:region_set_attribute - Dieser Effekt ist nicht auf der Region-Effekt-Liste! ",
		[31] = "ERROR: func: rac:can_player_set_region - Dir fehlt das Privileg 'region_set! ",
		[32] = "ERROR: func: rac:can_player_set_region - Das Gebiet ist zu schmal (x)!",
		[33] = "ERROR: func: rac:can_player_set_region - Das Gebiet ist zu schmal (z)!",
		[34] = "ERROR: func: rac:can_player_set_region - Das Gebiet ist zu schmal (y)!",
		[35] = "ERROR: func: rac:can_player_set_region - Das Gebiet ist zu breit (x)!",
		[36] = "ERROR: func: rac:can_player_set_region - Das Gebiet ist zu breit (z)!",
		[37] = "ERROR: func: rac:can_player_set_region - Das Gebiet ist zu hoch (y)!",
		[38] = "ERROR: func: rac:can_player_set_region - Andere Gebiete sind davon betroffen, du kannst das so nicht claimen!",
		[39] = "ERROR: func: rac:get_region_attribute - The region_attribute did not fit!",
		[40] = "ERROR: func: rac:command_help - Dir fehlt das Privileg 'interact'!",
		[41] = "ERROR: func: rac:command_pos - Dir fehlt das Privileg 'region_set! ",
		[42] = "ERROR: func: rac:command_pos - Kein Spieler mit dem Namen gefunden!",
		[43] = "ERROR: func: rac:command_set - Kein Spieler mit dem Namen gefunden!",
		[44] = "ERROR: func: rac:command_set - Dir fehlt das Privileg 'region_set! ",
		[45] = "ERROR: func: rac:can_player_set_region - Kein Spieler mit dem Namen gefunden! ",
		[46] = "ERROR: func: rac:region_set_attribute - der Gebietsnamen ist zu kurz! ",
		[47] = "ERROR: func: rac:region_set_attribute - der Gebietsnamen ist zu lang! ",
		[48] = "ERROR: func: rac:delete_region - No region with this ID! ",
		[49] = "info: Falsche Region_ID eingegeben! ",
		[50] = "ERROR: func: rac:get_region_at_pos - keine Region an dieser Position gefunden!",
		[51] = "ERROR: func: rac:check_region_attribute_version - unpassenden Effect gefunden!",
		[52] = "ERROR: func: rac:check_region_attribute_version - keine City und keine Zone gefunden, setzte default!",
		[53] = "ERROR: func: rac:can_player_set_region - Das Gebiete hat kein 'claimable' gesetzt!",
		[54] = "ERROR: func: rac:export - keine Data-Tabnelle bekommen",
		[55] = "ERROR: func: rac:import - ERROR: File does not exist! ",
		[56] = "ERROR: func: rac:command_status - Dir fehlt das Privileg 'interact'!",
		[57] = "ERROR: func: rac:command_show - Dir fehlt das Privileg 'region_admin'!",
		[58] = "Info: func: register_chatcommand(\"region\" - RegionStore wurde erfolgreich exportiert.",
		[59] = "ERROR: func: register_chatcommand(\"region\" - Dir fehlt das Privileg 'region_admin'!",
		[60] = "ERROR: func: load_regions_from_file - Der Check-Value ist noch erlaubt!",
		[61] = "ERROR: func: get_region_at_pos - mehr als 3 Regionen an diesr Position gefunden",
		[62] = "ERROR: func: can_interact - 2/3 Regionen gefunden, sei dürfen so ab er nicht liegen",
		[63] = "ERROR: func: can_interact - es liegen mehr als 3 Regionen an dieser Position, das darf nicht sein!!!!",
		[64] = "ERROR: func: command_set - Pos1 fehlt",
		[65] = "ERROR: func: command_set - Pos2 fehlt",
		[66] = "ERROR: func: command_set - region_name zu kurz",
		[67] = "msg: func: rac:get_region_center_by_name_and_pos - keine Region an dieser Position gefunden!",
		[68] = "ERROR: func: rac:command_border - Dir fehlt das Privileg 'interact'!",
		[69] = "ERROR: func: rac:can_player_set_region - Dir fehlt das Privileg 'region_set! ",
		[70] = "msg: Invalid usage.  Type \"/region help {command}\" for more information.",
		[71] = "ERROR: func: command_set - region_name zu lang!",
		[72] = "ERROR: func: can_player_set_region - Bezeichner Zone1 ist gleich Zone2.",
		[73] = "ERROR: func: can_player_set_region - Mehr als 2 Zonen überlappen.",
		[74] = "ERROR: func: command_compass - keine ID übergeben!",
		[75] = "ERROR: func: command_compass - Dir fehlt das Privileg region_admin!",
		[76] = "ERROR: func: register_globalstep - keine ID gesetzt",
		[77] = "ERROR: func: rac:command_player_regions - Dir fehlt das Privileg 'region_admin'!",
		[78] = "ERROR: func: rac:command_player_regions - There is no Player with this name!",
		[79] = "info: func: rac:command_max_y - Keine ID angegeben. '/region max_y ID'",
		[80] = "info: func: rac:command_max_y - Du bist nicht der Besitzer",
		[81] = "info: func: rac:command_max_y - keine Admin-Berechtigung",
		[82] = "info: func: rac:command_max_y - Diese Region hat schon die maximale Höhe!",
		[83] = "info: func: rac:command_max_y - Diese Region kann nicht so hoch / tief werden!",
		[84] = "info: func: rac:regions_by_zone - keine Admin-Berechtigung",
		[85] = "info: func: rac:command_pvp - keine Admin-Berechtigung",
		[86] = "info: func: rac:command_pvp - Falscher Aufruf des Command 'region pvp' Tippe \"/region help pvp\" für mehr Informationen.",
		[87] = "info: func: rac:command_mvp - keine Admin-Berechtigung",
		[88] = "info: func: rac:command_mvp - Falscher Aufruf des Command 'region mvp' Tippe \"/region help mvp\" für mehr Informationen.",
		[89] = "info: func: rac:command_claimable - keine Admin-Berechtigung",
		[90] = "info: func: rac:command_claimable - Falscher Aufruf des Command 'region claimable' Tippe \"/region help claimable\" für mehr Informationen.",
		[91] = "info: func: rac:command_protected - keine Admin-Berechtigung",
		[92] = "info: func: rac:command_protected - Falscher Aufruf des Command 'region protected' Tippe \"/region help protected\" für mehr Informationen.",
		[93] = "info: func: rac:command_effect - keine Admin-Berechtigung",
		[94] = "info: func: rac:command_effect - Falscher Aufruf des Command 'region effect' Tippe \"/region help effect\" für mehr Informationen.",
		[95] = "info: func: rac:command_change_zone - keine Admin-Berechtigung",
		[96] = "info: func: rac:command_change_zone - Falscher Aufruf des Command 'region effect' Tippe \"/region help change_zone\" für mehr Informationen.",
		[97] = "info: func: rac:command_rename - keine Admin-Berechtigung",
		[98] = "info: func: rac:command_rename - Falscher Aufruf des Command 'region effect' Tippe \"/region help rename\" für mehr Informationen.",
		[99] = "info: func: rac:command_own - keine Admin-Berechtigung",
		[100] = "info: func: rac:command_set_min - zu wenige Parameter übergeben",

	}
